# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Projects\Lab2\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(762, 732)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAcceptDrops(False)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBoxStrategyACount = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxStrategyACount.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.spinBoxStrategyACount.setFont(font)
        self.spinBoxStrategyACount.setMinimum(1)
        self.spinBoxStrategyACount.setProperty("value", 3)
        self.spinBoxStrategyACount.setObjectName("spinBoxStrategyACount")
        self.horizontalLayout_2.addWidget(self.spinBoxStrategyACount)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.spinBoxStrategyBCount = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxStrategyBCount.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spinBoxStrategyBCount.setFont(font)
        self.spinBoxStrategyBCount.setMinimum(1)
        self.spinBoxStrategyBCount.setProperty("value", 3)
        self.spinBoxStrategyBCount.setObjectName("spinBoxStrategyBCount")
        self.horizontalLayout_2.addWidget(self.spinBoxStrategyBCount)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lineEditMaxError = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditMaxError.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEditMaxError.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEditMaxError.setFont(font)
        self.lineEditMaxError.setInputMask("")
        self.lineEditMaxError.setObjectName("lineEditMaxError")
        self.horizontalLayout_5.addWidget(self.lineEditMaxError)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.spinBoxMaxIterationCount = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxMaxIterationCount.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.spinBoxMaxIterationCount.setFont(font)
        self.spinBoxMaxIterationCount.setMinimum(10)
        self.spinBoxMaxIterationCount.setMaximum(1000000)
        self.spinBoxMaxIterationCount.setProperty("value", 100)
        self.spinBoxMaxIterationCount.setObjectName("spinBoxMaxIterationCount")
        self.horizontalLayout_5.addWidget(self.spinBoxMaxIterationCount)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.tableWidgetStrategyMatrixInput = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetStrategyMatrixInput.sizePolicy().hasHeightForWidth())
        self.tableWidgetStrategyMatrixInput.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidgetStrategyMatrixInput.setFont(font)
        self.tableWidgetStrategyMatrixInput.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tableWidgetStrategyMatrixInput.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidgetStrategyMatrixInput.setAlternatingRowColors(False)
        self.tableWidgetStrategyMatrixInput.setShowGrid(True)
        self.tableWidgetStrategyMatrixInput.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidgetStrategyMatrixInput.setWordWrap(False)
        self.tableWidgetStrategyMatrixInput.setRowCount(3)
        self.tableWidgetStrategyMatrixInput.setColumnCount(3)
        self.tableWidgetStrategyMatrixInput.setObjectName("tableWidgetStrategyMatrixInput")
        self.tableWidgetStrategyMatrixInput.horizontalHeader().setVisible(False)
        self.tableWidgetStrategyMatrixInput.horizontalHeader().setDefaultSectionSize(35)
        self.tableWidgetStrategyMatrixInput.horizontalHeader().setMinimumSectionSize(35)
        self.tableWidgetStrategyMatrixInput.verticalHeader().setVisible(False)
        self.tableWidgetStrategyMatrixInput.verticalHeader().setDefaultSectionSize(35)
        self.tableWidgetStrategyMatrixInput.verticalHeader().setMinimumSectionSize(35)
        self.verticalLayout_2.addWidget(self.tableWidgetStrategyMatrixInput, 0, QtCore.Qt.AlignHCenter)
        self.pushButtonCalculate = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCalculate.sizePolicy().hasHeightForWidth())
        self.pushButtonCalculate.setSizePolicy(sizePolicy)
        self.pushButtonCalculate.setAutoFillBackground(False)
        self.pushButtonCalculate.setObjectName("pushButtonCalculate")
        self.verticalLayout_2.addWidget(self.pushButtonCalculate)
        self.tableWidgetSolution = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetSolution.sizePolicy().hasHeightForWidth())
        self.tableWidgetSolution.setSizePolicy(sizePolicy)
        self.tableWidgetSolution.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tableWidgetSolution.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidgetSolution.setObjectName("tableWidgetSolution")
        self.tableWidgetSolution.setColumnCount(0)
        self.tableWidgetSolution.setRowCount(0)
        self.tableWidgetSolution.verticalHeader().setVisible(True)
        self.verticalLayout_2.addWidget(self.tableWidgetSolution)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.tableWidgetAnswer = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetAnswer.setMaximumSize(QtCore.QSize(16777215, 120))
        self.tableWidgetAnswer.setObjectName("tableWidgetAnswer")
        self.tableWidgetAnswer.setColumnCount(0)
        self.tableWidgetAnswer.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidgetAnswer)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 762, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Метод Брауна-Робинсона"))
        self.label_2.setText(_translate("MainWindow", "Количество стратегий игрока А"))
        self.label_3.setText(_translate("MainWindow", "Количество стратегий игрока Б"))
        self.label_5.setText(_translate("MainWindow", "Максимальная ошибка"))
        self.lineEditMaxError.setText(_translate("MainWindow", "0.1"))
        self.label_6.setText(_translate("MainWindow", "Максимальное количество итераций"))
        self.pushButtonCalculate.setText(_translate("MainWindow", "Применить метод Брауна-Робинсона"))
        self.label_4.setText(_translate("MainWindow", "Ответ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

